apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    tier: backend

---

apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    tier: database
