apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  serviceAccountName: aws-ecr-access-sa
  containers:
    - name: kaniko
      imagePullPolicy: IfNotPresent
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
  restartPolicy: Never
